### ISSUE TITLE
Doesn't work with Vimeo anymore

### ISSUE THREAD

**Issue by ciorici** [deponeWD/video#2]
Hello!

I've checked several Vimeo videos, but this tool doesn't work anymore.

Any ideas if Vimeo changed something recently?

Thank you!

**Comment by deponeWD** [comment]
Thanks for pointing that out @ciorici 
I will have a look asap.

**Comment by deponeWD** [comment]
@ciorici broken thumbnail uri for videos hosted on vimeo is fixed.

**Comment by alien999999999** [comment]
It doesn't seem to work for me: `https://player.vimeo.com/video/500401358` ?

**Comment by deponeWD** [comment]
@alien999999999 the tool only works with public content.

**Comment by ciorici** [comment]
It still works fine with non-private Vimeo videos.

**Comment by deponeWD** [comment]
Thanks for pointing this out @ciorici

**Comment by alien999999999** [comment]
that link should be public content? or am i mistaken?
